Path Sequences
martinescardo/TypeTopology pull request #205
Opened 2023-10-11 15:30 UTC by ettorealdrovandi

It took a long time, but this is an almost word-for-word port of the path sequences library in https://github.com/HoTT/HoTT-Agda.

I have tried to limit the overuse of wild unicode characters for function names.

2023-10-11 16:25 UTC, martinescardo requested changes
Very nice you ported this, which should be very useful! 

General stylistic comments: (1) We prefer indentation by 1 space everywhere (although some portions of `TypeTopology` currently violate this). (2) We prefer lines that are not longer than 80 characters (so that we can have at least to parallel code windows open). (3) We usually use one, rather than two lines to separate definitions. 

In any case, your code looks good. Thanks!

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Ap.lagda
> +     ap₂ f refl (p ∙ [ t ↓])              ＝⟨ ap₂-refl-left f _ ⟩
Would you mind using indentation of 1 space?

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Ap.lagda
> +  ≡-＝-nat₂ {y = y} (p ◃∙ s) [] =  ap₂ f (p ∙ [ s ↓]) refl  ＝⟨ ap₂-refl-right f _ ⟩
Please indent as you did in line 142 to avoid long lines.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Ap.lagda
> +  ≡-＝-nat₂ (p ◃∙ s) (q ◃∙ t) = ap₂ f (p ∙ [ s ↓]) (q ∙ [ t ↓]) ＝⟨ ap₂-∙ f p ([ s ↓]) q ([ t ↓]) ⟩
Same indentation request.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Concat.lagda
> +              [ (p ◃∙ s) ↓] ∙ [ [] ↓]  ＝⟨ refl-right-neutral [ (p ◃∙ s) ↓] ⁻¹ ⟩
Indentation of 1 space please.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Concat.lagda
> +              [ (p ◃∙ s) ↓] ∙ [ (q ◃∙ t) ↓]  ＝⟨ refl ⟩
Same.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Inversion.lagda
> +seq⁻¹-involutive (p ◃∙ s) = seq⁻¹ (seq⁻¹ s ∙▹ (p ⁻¹))      ＝⟨ seq⁻¹-∙▹ (seq⁻¹ s) (p ⁻¹) ⟩
Break line after `=` and indent by 1 please.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Inversion.lagda
> +seq⁻¹-left-inverse s = ＝ₛ-in (
Same.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Inversion.lagda
> +seq⁻¹-right-inverse s = ＝ₛ-in ( [ s ∙≡ seq⁻¹ s ↓]     ＝⟨ [↓]-hom s (seq⁻¹ s) ⁻¹ ⟩
Same.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Inversion.lagda
> +Alternative names
Full stop.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Reasoning.lagda
> +  which awaits implementation once I figure out how to deal with the global univalence in UF.HLlevels
Full stop. (Everywhere please.)

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Reasoning.lagda
> +  This closes
Full stop.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Reasoning.lagda
> +  infixr 10 _＝ₛ⟨id⟩_
Blank line here please.

2023-10-11 16:25 UTC, martinescardo commented on source/PathSequences/Rotations.lagda
> +                    r ∙≡ (seq⁻¹ s ∙▹ (q ⁻¹))               ＝ₛ⟨ ＝ₛ-in (ap ≡-to-＝ (∙≡-assoc r (seq⁻¹ s) ((q ⁻¹) ◃∎) ⁻¹)) ⟩
Indentation by 1 please.

2023-10-11 16:28 UTC, martinescardo reviewed
One more thing: Please check your flags. Please remove `--auto-inline` (because it is in `typetopology.agda-lib`), however, please *keep* `--without-K` (for emphasis!) and `--safe`. Thanks!

2023-10-12 01:11 UTC, ettorealdrovandi commented
I think I got all the changes done

2023-10-12 11:55 UTC, merged