Modular Group as a mutual inductive type
martinescardo/TypeTopology pull request #214
Opened 2023-10-17 20:37 UTC by lane-core

This is a construction of the Modular Group PSL2(Z) utilizing a mutual inductive type. I will quote from the preamble of the Type declaration to contextualize the formalization presented here. This will serve as a base for future modules I will be adding to this folder.
```
To summarize the construction, we have E and S on the 𝓢 side, with little S
taking elements from the other type 𝓡. Then we have little R and R² in 𝓡,
taking elements from 𝓢 to construct its members; hence 𝓡 is strictly
dependent on 𝓢, and 𝓢 has the zero-level constructors, while successors for
both must be strictly alternating between types. Having a canonical S and E,
we obtain canonical representations of the words R/R² by right-composition
with the identity element. Thus we can form SR/SR² and R²S/RS evidently,
and achieve the ability to form every possible word in PSL₂ℤ generated by
the elements S and R in this type in irreducible form. Also to note, we can
interpret the action of η and θ constructors as essentially a representation
of the identity element from the left rather than the right side. The overall
methodology I pursued was to keep as few cases as possible for each branch
of pattern matching, so as to express the most efficient construction possible.

My overall intentions for this series of modules is as follows:
 1. Provide a base for research into the formalization of the Modular Group
  by purely synthetic/symbolic methods; 𝓜 can then be composed with other
  types to research specific fields of interest
 2. Studying the relationship between modular forms and Gosper's bihomographic
  algorithm originally presented in his continued fraction arithmetic paper
 3. On the basis of (2), develop a new formalization of rational and real
  arbitrary-precision arithmetic with a type formalized along the lines of
  Bertot and Niqui's work in the QArith libraries. Where the approach will
  differ here is the use of symbolic rather than analytic methods of
  computing that arithmetic, acting directly upon symbolic representations
  of matrices in 𝓜 and canonical representatives in ℚ or ℝ rather than
  translating between them and natural number or integer types.
 4. Investigate whatever connections are appropriate for the subjects pursued
  above with Univalent mathematics in general.
```

2023-10-17 20:58 UTC, martinescardo commented
Thanks. I'll ask @UlrikBuchholtz to help to review this.

2023-10-17 21:17 UTC, lane-core commented
Thank you!

2023-11-27 14:43 UTC, martinescardo commented
Here are some requests and suggestions before @UlrikBuchholtz completes his review:

 * In order to convince Ulrik and me that you did implement the modular group, and not some random group, I think you should state and prove its universal property, namely that it is presented by generators `S` and `T` and relations `S^2 = 1` and `(ST)^3=1`, as discussed [here](https://en.wikipedia.org/wiki/Modular_group#Presentation).
 
 In `TypeTopology` you can state this by saying that for any other group `G` with elements `s` and `t` satisfying the above identities there is a unique homomorphism from your group to `G` that maps `S` to `s` and `T` to `s`. I guess you have already developed enough material here to be able to prove this (you already have some induction principles which are close to this). I suggest that you add a new file `UniversalProperty` with this. 
 
 * Please move the whole tree `ModularGroup` from `source` to `Groups`.
 * Please add an index file inside the directory `ModularGroup`. In that index file, add a brief explanation in English saying in which order the files should be read, and briefly mentioning what they do (for example, you can follow the convention of the file `Quotient.index`).
 * Please import `ModularGroup.index.lagda` from `Groups.index`. 
 * I will have more mundane suggestions later in my own review of the code.
Thanks!

2023-11-27 15:25 UTC, lane-core commented
I will be working on this! Thanks.

2023-11-27 16:22 UTC, martinescardo commented
Maybe the directory `ModularGroup` can be renamed to just `Modular`, given that it will imported as `Groups.Modular` if you move it to `Groups`.

2023-11-28 11:20 UTC, martinescardo commented
1. Please use the `Group` definition of `is-hom`.
 2. There are lot of instances in `TypeTopology` where we first proved something, and then something more general (an example is `InjectiveTypes.MathematicalStructures` and `InjectiveTypes.MathematicalStructuresMoreGeneral`). I am in favour, in your case, of doing the same thing.

2024-01-02 12:51 UTC, martinescardo requested changes
Just to make official what I requested before: please state and prove the universal property before we review this in more detail. Thanks.

2024-01-09 06:19 UTC, lane-core commented
just to update you on the status, I've started work on this. so far I've defined an induction principle based on generators S and T (T being defined as SR, which reduces to T in this representation). I've used it to define a function from Group PSL2Z to an arbitrary group, and it has the requisite is-hom properties. For fun I also defined one by case matching instead of the induction function and shown functional equivalence between the two. I am where I must prove uniqueness, and this is the point where I have to become clever. I'll submit a force push when its ready.

2024-02-22 16:46 UTC, martinescardo commented
I wonder if there has been any progress regarding the work of this PR.

2024-02-22 17:22 UTC, lane-core commented
Yes I will submit an update by this week

2024-02-28 16:49 UTC, lane-core commented
Wanted to give a quick update, I did a lot of refactoring of my Universal Property file, I am currently running into an issue when I assume an arbitrary hom `f` of a group `G`. I must prove that `f` converts our canonical `S` into our `S` from `G`, but try as I might to use the homomorphism property of `f`, I cannot split up our `S` such that applying the homomorphic property does not just recreate the original proof goal (after eliminating the unit that is generated from splitting `S` into `S * E`. Would you have me update the PR with the current state of the proof?

2024-02-29 15:57 UTC, martinescardo commented
Sure, you can update the PR!

2024-04-23 21:30 UTC, ayberkt commented
Any updates on this @lane-core?

2024-08-29 22:15 UTC, lane-core commented
Hi @martinescardo, I realize I've left this PR open even after promising to complete the required revisions; I hope that you won't mind the length of what follows, but I want to write a thoughtful summary of my experience and what my endeavors eventually led to, which I hope explains and mitigates my considerable absence somewhat. Don't think for a moment I wasn't appreciative that you were interested in reviewing this contribution. Rather I hope you'll agree with me that that the path I was led onto will be much more fruitful for any future contributions I might submit towards your consideration in the long run; I am deeply interested in your thoughts on the below, specifically towards the end, because I am aware of work of yours that touches upon exact real arithmetic, and I've been able to surmise some interesting connections here due to my idiosyncratic journey in this subject.

To summarize where I left off working on this PR: my difficulty began when I found that I could prove most of the cases required to show an equivalence between types, except for the base case, where I had hit a wall. I had proven a lemma of the form:
```
hom-is-prop : (f : Γ → 𝔾) → is-prop (is-hom PSL₂Z G f)
where Γ is my mutually inductive type and 𝔾 is the generic group presented by generators and quotient identities
```
I had shown that the homomorphism between the group characterized by the generators `S, T` along with their corresponding quotienting axioms and my construction was a unique map. However when it came to being able to show:
```
Γ-homo-is-unique : ∃! f ꞉ (Γ → 𝔾) , is-hom PSL₂Z G f
```
I found certain difficulty. I had chosen an unfortunate approach, which was to try to derive straightaway that `f = h` where h was the map from `𝔾 → Γ`. To do that require me to define some lemmas:
```
f-S : Π x ꞉ Γ , f (s (x)) ＝ ｓ (f x)
f-T : Π x ꞉ Γ , f (t (x)) ＝ ｔ (f x)
```
where the special character letters are functions encoding left-composition of their corresponding symbols in the generic group. The snag was: due to my choice of having two base unit constructors in my type, namely `E` and `S`, I was playing ring-around-the-rosie trying to demonstrate the base cases for all these lemmas. An immediate solution was obvious: refactor the type so that we have a canonical unit constructor upon which we layer the other (mutual) constructors, and then this issue goes away. Then I'd rewrite the modules, which I foresaw would be a bit tedious but trivial given the familiarity I gained with this sort of construction.

I was not satisfied with an immediate solution however. I saw that my hack-and-slash adventures with type theory had reached a limit, and that it was better for me to digest a more sophisticated approach to the subject. Namely, catching up to the big ideas in univalent mathematics and to thoroughly digest the fundamentals of homotopy type theory beyond elementary DTT, which has been enriching, illuminating, and deeply fascinating.

An important and influential line of investigation on my part has come from attempting to understand certain constructions from graphical theories of computation, specifically the school of Lafont, Mazza, and so on, applying thinking from HoTT in this domain in relation to the new potential interpretations given to the aspects of proof theory that these graphical methods generalize. This has been a fruitful and lively avenue for me to investigate, and it is currently leading me towards an exploration of Braided/Ribbon categories in particular.

As I began to imagine the possible ways to investigate my current focus of research, I was reminded me of this pull request. I observed that this construction as an instructive and elementary example that will benefit from a certain approach I've stumbled onto. This week I will recode this set of modules, and soon after I'll continue onto Hecke Groups-- specifically because the notion of a mutually inductive type generating a universe of elements by constructors formed with vectors (`Fin i -> Hecke j` for some `i, j`), whose target is its own ever-expanding domain, forms an intriguing example for me to explore at the present moment.

Forgive me if I am just rediscovering some observation in a paper I don't know of yet, in which case, kindly point me to that direction if anything comes to mind, but I'd share my current thinking on this specifically to see if anything comes to mind for you: I believe there is a way to interpret Hecke groups that offers illuminating analogies for fundamental concerns in type-theoretic semantics, and can serve to connect this field to the rich literature on Modular/Hecke groups. 

To start with, lets examine the action of S, and consider this thought experiment: we begin by interpreting `S` as an interpretation of `not` in the booleans, which has the quality that composing it twice gives the identity in PSL2Z. Now lets turn to consider the action of S in SL2Z, which has the quotienting rule equating S^4 to the identity. I believe that one can interpret the S generators here as 2-braids in a 3-dimensional space, where:
```
S ~ not: 0 crosses under 1
S^2 ~ id: 0 crosses under 1, which crosses over back to 0; note that the twisting here has the characteristic that one cannot pull the wires back to being straight, they are threaded between each other.
```
While S^2 is observationally equivalent to id from the perspective of the signal traversing the wire, in the ambient context one can strictly distinguish a signal traversing this pathway's twists from that path taking no twists. We achieve a return to the original identity by the time we reach S^4 if we interpret S^3 as an application of an unraveling where we pull the wire back and under, and do so again at S^4 such that we are left with a pair of parallel wires; this now expresses `S^0 = id` in the appropriate sense. Likewise, if we are to begin from some word whose head is T and left-compose it with S^-1, we would perform a twist of 1 under 0, with an analogous procedure for computing the action of the positive inverse S^1 upon this negative S^-1. So here we see an interpretation of PSL2Z as a truncation of this 3rd dimension to 2 dimensions, where twists are free to be pulled back to running parallel.

There is a degree of subtlety for how to characterize the action of ST in this interpretation. I believe the answer lies in interpreting the fact that elements of Hecke group `q` are isomorphic to the products of the cyclic groups 2 and q. Fundamentally, each word may be interpreted within an ambient space of braidings between indices numbered up to `2 * q` (in the modular group's case, we consider braidings from `Fin 6 -> Fin 6`, as the group is isomorphic to `C2*C3`). 

For simplification of this interpretation, let's return to the Modular Group case (PSL2Z). 

In the Monoid composed by these group elements, each of the words actually demarcates a specific linear path taken through this chain of composed elements, which are interpreted here by string diagrams expressing braidings/permutation sets between the elements of C2*C3 formed by unique compositions of `S, R`. Or in other words, we consider the automorphisms of `C2*C3`. But there is another way to characterizer what is happening here: we consider that what we have here are mutually paramaterized diagrams, which on one side is a 2-braid whose wires are paramaterized over 3-braids; this is the "S" side. Vice versa on words whose head is R we can turn to consider 3-braids whose wires are paramaterized over 2-braids.

Under this interpretation, we see very well why we can form a canonical presentation of elements in PSL2Z: because the twists/braidings are in a 2d space, *there is only one way* to arrive at a given word which expresses a specific path comprised of various twists and untwists along these mutually paramaterized diagrams, and this is exactly why the composable words in PSL2Z can be shown to form a set. Whereas, I conjecture based on the immediate im [...]

2024-08-30 08:46 UTC, martinescardo commented
Thanks for the discussion. I am happy for you to take the approach you suggest, if you think it will be more fruitful.

I am pinging @UlrikBuchholtz in case he has something to remark about this.

2026-01-16 11:12 UTC, martinescardo commented
Is there any intention to continue with this?

2026-01-16 20:02 UTC, biocini commented
@martinescardo Yes, I'm starting work on this again. I apologize for the delay. I was not equipped to finish this PR at the time, and I needed to go on an extensive detour to deepen my knowledge. I feel ready to wrap this up now integrating your revision requests.

2026-01-20 21:09 UTC, biocini commented
Quick update: I've achieved all the goals requested (including the UniversalProperty module) and I'm polishing up my results to force push to this PR sometime in the next few days. Revisiting this problem I came up with something more interesting by taking a stab at reformulating this mutual inductive type in line with ideas from Bass-Serre theories. 

This was a happy accident of discovery where many results came quickly adapting from some first passes with this theory. This handily convinced me of the viability of the approach, but I still feel I have a shallow understanding of what I've just accomplished. I'd like to spend time formally developing this connection and Bass-Serre theory constructions more generally in future commits. Of course, only after we've sorted out everything that needs to make the specific Modular Group type presentable within TypeTopology so we can get this off the stack :)

For potential future work there is a distinct motivation arising from my personal research for me to investigate Bass-Serre forests in HoTT (I see: https://arxiv.org/abs/2107.09576v2 as a great departure point). I've been studying definitions of univalent higher categories/groups in the literature and this seems like a nice way to explore techniques I've been developing for an important (and instructive) object. Once I'm done with this PR I'll be looking into that prospect.

Quick note with regards to the universal property @martinescardo: although you had mentioned the description with generators `S,T` to specify the property, I went with fixing the group description of PSL2Z as having two generators `S,R` quotiented by `SS = E` and `RRR = E`. It seems evident to me that we can proceed this way WLOG, because given any Group description based on `S,T` having the corresponding quotient laws entails I can satisfy the description based on `R` by fixing `R = ST`. The converse description holds by fixing `T = SR` along with some tedious but trivial path algebra.

2026-01-22 03:18 UTC, biocini commented
I've gone ahead and submitted a full set of the new modules under Groups.ModularGroup, as requested @martinescardo @UlrikBuchholtz

https://github.com/martinescardo/TypeTopology/pull/214/changes/c32fe05b26b10754271072948c9eef2324786096

2026-01-22 13:07 UTC, martinescardo commented
Great! Is this ready for review now?

2026-01-22 13:12 UTC, martinescardo commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +   -- show the homotopy between the morphism and hmap
Use code blocks for the comment, please.

2026-01-22 13:12 UTC, martinescardo commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +     -- It respects the algebra
(Everywhere.)

2026-01-22 13:12 UTC, martinescardo commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +     -- Any homomorphism respecting the algebra equals the canonical one
(Including here.)

2026-01-22 20:21 UTC, biocini commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +   -- show the homotopy between the morphism and hmap
fixed in new commit

2026-01-22 20:21 UTC, biocini commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +     -- It respects the algebra
fixed in new commit

2026-01-22 20:22 UTC, biocini commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +     -- Any homomorphism respecting the algebra equals the canonical one
fixed in new commit

2026-01-22 20:22 UTC, biocini commented
> Great! Is this ready for review now?

yes go right ahead

2026-01-30 22:23 UTC, biocini commented
sorry to ping! it said that changes were requested and I was attempting to let the system know I had responded to the change request

2026-01-30 22:45 UTC, martinescardo commented
> sorry to ping! it said that changes were requested and I was attempting to let the system know I had responded to the change request

Thanks for addressing all points. We are working on this, both @UlrikBuchholtz and I. But we are both busy, and so it may take a while.

(You did take your time yourself. :-) ).

2026-01-30 22:52 UTC, martinescardo commented
No worries! I am glad you finally completed this.

2026-01-30 22:52 UTC, martinescardo commented
We'll get back to you.

2026-01-30 23:34 UTC, biocini commented
> > sorry to ping! it said that changes were requested and I was attempting to let the system know I had responded to the change request
> 
> Thanks for addressing all points. We are working on this, both @UlrikBuchholtz and I. But we are both busy, and so it may take a while.
> 
> (You did take your time yourself. :-) ).

No rush! In fact you are justified to take as much time reviewing it as I did to submit :) In the interim I may look over this and make minor modifications if it suits, but if so I will log exactly what in this thread. Consider it reviewable in any respect.

2026-03-27 18:53 UTC, martinescardo commented
I will get back to this asap.

2026-04-10 15:15 UTC, martinescardo commented
Hi @lane-core . I've discussed this with colleagues to check that you formalized the right universal property, and we are satisfied that this is the case. So now, with this out of the way, I will proceed to a more routine review for style etc. I should be able to do this relatively soon.

2026-04-10 15:15 UTC, martinescardo commented
Sorry for the long delay!

2026-04-10 15:42 UTC, martinescardo reviewed
Thanks for this contribution. This is very nice, and beautifully written, using the TypeTopology style (with one or two minor exceptions). 

As I said, some of us have checked that you have formulated the right universal property, which is what caused delay (in addition to all of us being busy), for which we apologize.

I will be able to merge after you make these minor stylistic modifications.

2026-04-10 15:42 UTC, martinescardo commented on source/Groups/ModularGroup/Type.lagda
> +{-# OPTIONS --safe --without-K --exact-split #-}
You should now remove `--exact-split` everywhere, because we made this default in the meantime.

2026-04-10 15:42 UTC, martinescardo commented on source/Groups/ModularGroup/UniversalProperty.lagda
> + r²-r-is-e alg =
Please check that you use indentation by 1 (rather than 2) as in this case.

2026-04-10 15:42 UTC, martinescardo commented on source/Groups/ModularGroup/UniversalProperty.lagda
> + r²-r-is-e alg =
(Everywhere.)

2026-04-10 15:42 UTC, martinescardo commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +                 → is-hom 𝓜 G φ
Bad indentation. Please make the colon and the arrow be at the same indentation level.

2026-04-12 04:32 UTC, lane-core commented
No apologies for the wait needed, it took me long enough myself. Happy it passed the mark! The modular group deserves a great presentation so I wanted to see to that (its one of my favorites).

I have certain extension modules that are half-way done, so down the line I may look into a second PR when I have time to finish those. There is a pretty clear route towards generalizing the methods here as well however that could be fruitful to pursue. Finishing my categories gist for TypeTopology is taking priority at the moment.

I will make these corrections and push to this pr by the end of the weekend!

2026-04-12 16:57 UTC, martinescardo commented
Great! I will try to be quick. But notice that I am attending a conference beginning today until the end of the week. Thanks.

2026-04-12 17:46 UTC, martinescardo commented
Oh, and one more thing. Please use the script `imports.sh` to make sure you are not importing more than is needed. All of us, during development, import files that eventually are not needed any more, and it is very difficult to detect this manually. So please run this script with your files, and remove unused imports. Thanks a lot!

2026-04-12 20:20 UTC, martinescardo commented
@ayberkt Would it be possible to run this script here automatically as part of the checks?

2026-04-13 09:30 UTC, ayberkt commented
> @ayberkt Would it be possible to run this script here automatically as part of the checks?

@martinescardo It should be possible to do that. We can get the list of files touched by a PR and run the redundant import check only on those.

2026-04-29 20:44 UTC, biocini commented on source/Groups/ModularGroup/Type.lagda
> +{-# OPTIONS --safe --without-K --exact-split #-}
done

2026-04-29 20:45 UTC, biocini commented on source/Groups/ModularGroup/UniversalProperty.lagda
> + r²-r-is-e alg =
done

2026-04-29 20:45 UTC, biocini commented on source/Groups/ModularGroup/UniversalProperty.lagda
> +                 → is-hom 𝓜 G φ
done

2026-04-29 21:23 UTC, lane-core commented
Apologies for the delay, happy to close this off. I've integrated all edits and cleaned up a typo and revised `respects-gen` verbiage to `respects-alg` in the last section of UniversalProperty.  I hope your conference went well @martinescardo, and I'll be back with other work soon enough.

2026-04-30 09:23 UTC, martinescardo approved these changes

2026-04-30 09:23 UTC, merged