H levels
martinescardo/TypeTopology pull request #236
Opened 2024-02-08 10:12 UTC by IanRay11

I needed to finish this proof, but you should probably review it.

2024-02-08 14:01 UTC, martinescardo commented
https://github.com/martinescardo/TypeTopology/pull/236/conflicts

2024-02-08 14:25 UTC, IanRay11 commented
Oh shoot. I thought I was pushing the same PR

2024-02-08 14:26 UTC, IanRay11 commented
I need to get some sleep and come back to this, again sorry

2024-02-08 14:56 UTC, martinescardo commented
No worries. Have a good rest.

2024-02-08 15:56 UTC, IanRay11 commented
You might want to review what I've added with the recent push @martinescardo

2024-02-08 16:03 UTC, martinescardo commented
OK. I will do later.

2024-02-09 12:09 UTC, martinescardo requested changes
Great. I required minimal notational changes only.

2024-02-09 12:09 UTC, martinescardo commented on source/UF/H-Levels.lagda
> +lemma : {X : 𝓤 ̇} → ((x x' : X) → is-contr (x ＝ x')) → is-prop X
`lemma` is not a good name for such a general fact. How about `is-prop-criterion`. But if you have a better idea, go ahead. Please just avoid `lemma`.

2024-02-09 12:09 UTC, martinescardo commented on source/UF/H-Levels.lagda
> +ℍ-is-next-level : (n : ℕ)
I would prefer `ℍ-is-of-next-hlevel` (two changes).

2024-02-10 10:31 UTC, martinescardo approved these changes

2024-02-10 10:31 UTC, merged