Making seperate PRs
martinescardo/TypeTopology pull request #303
Opened 2024-08-07 20:52 UTC by IanRay11

2024-08-08 06:19 UTC, tomdjong commented
Some context: This is the first of three PRs on truncations and connectedness as I've asked @IanRay11 to split up his work.

2024-08-08 07:04 UTC, tomdjong requested changes
Thanks @IanRay11! :smile: 

Some additional comments that I couldn't make in place because these lines were not touched by the commit:

- Can you use `＝-retract` (from `UF.Retracts` and which I've just added) in `level-closed-under-retract` and fix the indentations to a single space in all the `hlevel-closed-under-`lemmas.

- In `hlevel-closed-under-retract`, `hlevel-closed-under-equiv` and `hlevel-closed-under-embedding`, the types should probably be implicit arguments.

- In `hlevel-closed-under-embedding`, the argument `n-above-one` isn't used, so you can do:
```
hlevel-closed-under-embedding (succ n) _ X Y (e , is-emb) Y-h-level x x' =
 hlevel-closed-under-equiv n (x ＝ x') (e x ＝ e x')
                           (ap e , embedding-gives-embedding' e is-emb x x')
                           (Y-h-level (e x) (e x'))
```

- In the equivalence reasoning of `ℍ-is-of-next-hlevel`, please put long long equivalences in a where clause, so that it looks like this
```
 X ≃⟨ I ⟩
 Y ≃⟨ II ⟩
 Z ■

 where
  I = some-long-equivalence
  II = some-other-long-equivalence
```

- Also in `ℍ-is-of-next-hlevel`, you can also just write `fe'` instead of `fe 𝓤 𝓤` and use `Π₂-is-prop` instead of `Π-is-prop` twice.

The comment about `fe'` applies elsewhere too.

2024-08-08 17:50 UTC, IanRay11 commented on source/UF/H-Levels.lagda
> +                   (fe' : Fun-Ext)
I removed the FunExt assumption and made fe : Fun-Ext. Then \ _ _ -> fe : FunExt. Is this sufficient? I couldn't find the proof of interderivability in the FunExt file.

2024-08-08 18:02 UTC, IanRay11 commented on source/UF/H-Levels.lagda
> +contr-implies-id-contr (c , C) x x' = (((C x)⁻¹ ∙ C x') , D)
Instead I am going to move the is-prop' introduction up.

2024-08-08 21:09 UTC, closed without merging

2024-08-09 06:27 UTC, tomdjong commented on source/UF/H-Levels.lagda
> +                   (fe' : Fun-Ext)
It's standard TypeTopology practice to do something like
```
private
 fe' : Fun-Ext
 fe' {𝓤} {𝓥} = fe 𝓤 𝓥
 ```

2024-08-09 06:27 UTC, tomdjong commented on source/UF/H-Levels.lagda
> +                   (fe' : Fun-Ext)
It really doesn't require a proof as the only difference is having the universes implicit or not.